/**
 * Single source of truth for the static route list used by the sitemap.
 *
 * Plain ESM (not `.ts`) on purpose: `scripts/generate-route-modified.mjs` is
 * invoked directly by `node` during `prebuild`, before any TypeScript
 * tooling runs, so it cannot import a `.ts` module. `app/sitemap.ts` imports
 * this same file (allowed by `allowJs` in tsconfig.json) so the two never
 * drift into two different route lists.
 *
 * `messageKey` is the best-effort next-intl namespace for the route, i.e.
 * the key used in `messages/en/index.ts` (which is also the JSON file's
 * basename: `messages/en/${messageKey}.json`). It is used only as a second,
 * best-effort signal for "did this route's content change" — a copy edit
 * shows up here even when the page component itself did not change. `null`
 * means no single message namespace backs the route (there is none to check).
 *
 * @typedef {{
 *   path: string,
 *   changeFrequency: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never",
 *   priority: number,
 *   messageKey: string | null,
 * }} StaticRoute
 *
 * @type {StaticRoute[]}
 */
export const routes = [
  { path: "", changeFrequency: "weekly", priority: 1.0, messageKey: "home" },
  { path: "/features", changeFrequency: "weekly", priority: 0.9, messageKey: "features" },
  { path: "/download", changeFrequency: "weekly", priority: 0.9, messageKey: "download" },
  { path: "/playground", changeFrequency: "weekly", priority: 0.8, messageKey: "playground" },
  { path: "/blog", changeFrequency: "daily", priority: 0.8, messageKey: "blog" },
  { path: "/news", changeFrequency: "daily", priority: 0.9, messageKey: "news" },
  { path: "/docs", changeFrequency: "weekly", priority: 0.8, messageKey: "docs" },
  { path: "/docs/getting-started", changeFrequency: "weekly", priority: 0.8, messageKey: "docs" },
  { path: "/docs/extension", changeFrequency: "weekly", priority: 0.7, messageKey: "docs" },
  { path: "/docs/sdk", changeFrequency: "weekly", priority: 0.7, messageKey: "docs" },
  { path: "/docs/oracle", changeFrequency: "weekly", priority: 0.7, messageKey: "docs" },
  { path: "/oracle", changeFrequency: "monthly", priority: 0.7, messageKey: "oracle" },
  { path: "/pqc", changeFrequency: "weekly", priority: 0.8, messageKey: "pqc" },
  { path: "/pqc/chat", changeFrequency: "weekly", priority: 0.7, messageKey: "pqcChat" },
  { path: "/about", changeFrequency: "monthly", priority: 0.6, messageKey: "about" },
  { path: "/contact", changeFrequency: "monthly", priority: 0.5, messageKey: "contact" },
  { path: "/guides", changeFrequency: "weekly", priority: 0.8, messageKey: "guides" },
  { path: "/projects", changeFrequency: "monthly", priority: 0.6, messageKey: "projects" },
  { path: "/widgets", changeFrequency: "monthly", priority: 0.7, messageKey: "widgets" },
  { path: "/pitch", changeFrequency: "monthly", priority: 0.5, messageKey: "pitch" },
  { path: "/media-kit", changeFrequency: "monthly", priority: 0.4, messageKey: "mediaKit" },
  { path: "/privacy", changeFrequency: "yearly", priority: 0.3, messageKey: "privacy" },
  { path: "/terms", changeFrequency: "yearly", priority: 0.3, messageKey: "terms" },
];

/**
 * The `app/[locale]/**\/page.tsx` file that renders a given static route
 * path (e.g. "/docs/getting-started" -> "app/[locale]/docs/getting-started/page.tsx",
 * "" -> "app/[locale]/page.tsx"). Returned as path segments relative to the
 * repo root so callers can `path.join(ROOT, ...segments)`.
 *
 * @param {string} routePath
 * @returns {string[]}
 */
export function sourceFileSegments(routePath) {
  const parts = routePath.split("/").filter(Boolean);
  return ["app", "[locale]", ...parts, "page.tsx"];
}

/**
 * The best-effort English message file backing a route's `messageKey`, as
 * path segments relative to the repo root, or `null` when the route has no
 * single namespace to check.
 *
 * @param {string | null} messageKey
 * @returns {string[] | null}
 */
export function messageFileSegments(messageKey) {
  if (!messageKey) return null;
  return ["messages", "en", `${messageKey}.json`];
}

/**
 * Pure lookup: given the route-modified map generated by
 * scripts/generate-route-modified.mjs (lib/generated/route-modified.json),
 * resolve the `lastModified` value for one static route path.
 *
 * Returns `undefined` — never a fabricated date — when the map has no entry
 * for the route, or when the map itself is empty/missing (which is exactly
 * what scripts/generate-route-modified.mjs writes when git is unavailable
 * or the clone is shallow: honest silence, not a uniform fallback).
 *
 * This is the one place app/sitemap.ts decides whether to include
 * `lastModified` for a static route, kept pure and dependency-free so it
 * can be unit tested without shelling out to git.
 *
 * @param {string} routePath
 * @param {Record<string, string> | null | undefined} modifiedMap
 * @returns {Date | undefined}
 */
export function resolveRouteLastModified(routePath, modifiedMap) {
  const iso = modifiedMap ? modifiedMap[routePath] : undefined;
  return iso ? new Date(iso) : undefined;
}
